### ISSUE TITLE
SyntaxError: Could not parse Task title

### ISSUE THREAD

**Issue by pfsmorigo** [google/gtasks-md#1]
Hello, thanks for his project! I just installed in my Ubuntu 20.04 box and the `gtasks-md auth` command worked, I think, but when I run `gtasks-md view`, I got the following error:

```
Traceback (most recent call last):
  File "/home/pfsmorigo/.local/bin/gtasks-md", line 8, in <module>
    sys.exit(main())
  File "/home/pfsmorigo/.local/lib/python3.10/site-packages/app/cli.py", line 62, in main
    view(service)
  File "/home/pfsmorigo/.local/lib/python3.10/site-packages/app/cli.py", line 141, in view
    _, text = fetch_task_lists(service)
  File "/home/pfsmorigo/.local/lib/python3.10/site-packages/app/cli.py", line 174, in fetch_task_lists
    return task_lists, task_lists_to_markdown(task_lists)
  File "/home/pfsmorigo/.local/lib/python3.10/site-packages/app/pandoc.py", line 94, in task_lists_to_markdown
    OrderedList(ORDERED_FIRST_ELEM, tasks_to_pandoc(task_list.tasks))
  File "/home/pfsmorigo/.local/lib/python3.10/site-packages/app/pandoc.py", line 49, in tasks_to_pandoc
    pandoc_tasks.append(task_to_pandoc(task, has_notes))
  File "/home/pfsmorigo/.local/lib/python3.10/site-packages/app/pandoc.py", line 75, in task_to_pandoc
    raise SyntaxError(f"Could not parse Task title {task.title}")
SyntaxError: Could not parse Task title
```

I'm using pandoc version 2.9.2.1-3ubuntu2. Maybe that's the reason?

Thanks in advance!

**Comment by jupblb** [comment]
Hi! Thank you for checking out this tool and filing the issue. I was able to reproduce this with having empty string as task title. I added support for it in https://github.com/google/gtasks-md/commit/b3ebf6bfad61321a2a2ddc166455a7b41b8baa67.

That being said, I did not intend to support such a scenario. Having a task with empty name will still cause an issue with the `edit` command because of the way Markdown content is parsed.

**Comment by pfsmorigo** [comment]
Oh cool. Those empty tasks are usually when you are using the app and press the enter after adding a task. I'm trying to use google tasks again after some years and there were lots of very old items there. I clean it up and remove the empty task and worked even using the current version. Thanks for this fix!
