### ISSUE TITLE
Pandoc 3.2 not supported

### ISSUE THREAD

**Issue by ahinkley** [google/gtasks-md#12]
When I execute runner.py I get the following:

```
/home/ahinkley/.local/lib64/python3.11/site-packages/pandoc/utils.py:62: UserWarning: 
Pandoc version 3.2 is not supported, we proceed as if pandoc 2.19.2 was used. 
The behavior of the library is undefined if the document models of these versions differ.
  warnings.warn(error)
Please run one of the subcommands.
```
When I run gtasks view I get
```
  warnings.warn(error)
Traceback (most recent call last):
  File "/home/ahinkley/.local/bin/gtasks-md", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/app/__main__.py", line 54, in main
    edit(service, editor, backup)
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/app/__main__.py", line 146, in edit
    old_task_lists, old_text = fetch_task_lists(service)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/app/__main__.py", line 174, in fetch_task_lists
    return task_lists, task_lists_to_markdown(task_lists)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/app/pandoc.py", line 91, in task_lists_to_markdown
    return pandoc.write(Pandoc(Meta({}), content))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/pandoc/__init__.py", line 355, in write
    pandoc(options)
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/plumbum/commands/processes.py", line 328, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/ahinkley/.local/lib64/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 64
Command line: | /usr/bin/pandoc -t markdown -o /tmp/tmp5ck2gfkq/output -f json /tmp/tmp5ck2gfkq/input.js
Stderr:       | JSON parse error: Error in $: Incompatible API versions: encoded with [1,22,2,1] but attempted to decode with [1,23,1].
```

**Comment by jupblb** [comment]
Pandoc 3.2 support has been recently added to [boisgera/pandoc](https://github.com/boisgera/pandoc) (gtasks-md depends on it). There is no fresh release yet, unfortunately.

**Comment by jupblb** [comment]
We no longer use Pandoc for markdown parsing.
